---
- name: installing httpd
  hosts: all
  become: true
  tasks:
  - name: install the httpd pkg
    yum:
      name: httpd
      state: latest

  - name: firewall allowing http
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: start the service
    service:
      name: httpd
      state: started
      enabled: true
